# Generated by Django 3.2.5 on 2021-08-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_newvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newvideo',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
