# Generated by Django 3.2.5 on 2021-08-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_newvideo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
    ]
