# Generated by Django 3.2.5 on 2021-08-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_video_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
