# Generated by Django 3.2.5 on 2021-08-08 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210808_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
